// Artifact library — UCB demo.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — Q2 2026',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-05-30',
    summary: 'Full Q2 Strategy-to-Action: ISP pillars, MO coverage (MO2 Gap highlighted), prioritised insights (AI1–AI5), proposed actions (A1–A9), Gap Radar, and MA ROMI framework proposal. Delivered to UCB sovereign cloud environment (Azure) — no data left the UCB-managed tenancy.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Med Info queries', 'Internal stakeholder interviews', 'AAD / EADV 2025 congress debriefs', 'PubMed'],
    sizeLabel: '2.5 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'AAD / EADV 2025 Debrief — Bimzelx HS & IL-17A/F Signal Analysis',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-06-03',
    summary: 'Synthesized read on HS and IL-17/IL-23 scientific themes at AAD and EADV 2025 — Bimzelx share-of-voice (71% in HS), competitor response tracking, KOL post-congress narrative shifts, and recommended MSL response actions for IL-17A/F differentiation conversations.',
    dataSources: ['AAD 2025 abstracts', 'EADV 2025 session transcripts', 'X / LinkedIn monitoring', 'KOL post-congress commentary'],
    sizeLabel: '2.2 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART3',
    title: 'KOL Public–Private Alignment Report — June 2026',
    type: 'pdf',
    agent: 'LUCA',
    taskType: 'KOL Intelligence Report',
    dateCreated: '2026-06-04',
    summary: 'Alignment scoring for 17 UCB portfolio KOLs across public (X, LinkedIn, Medscape) and private (MSL interaction) channels. Flags 2 divergence cases for immediate action — Dr. Zouboulis (competitor co-authorship) and Dr. Moshé (low engagement). Includes recommended scientific exchange briefs.',
    dataSources: ['MSL interaction logs', 'X / LinkedIn monitoring', 'PubMed co-authorship analysis', 'Congress programme tracking'],
    sizeLabel: '1.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'Bimzelx HS Real-World Evidence Synthesis — Biologic-Experienced Patients',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Field Insight Synthesis',
    dateCreated: '2026-05-15',
    summary: 'Aggregated MSL-reported and registry-sourced real-world outcomes for Bimzelx in biologic-experienced HS patients (n=312 patients across 18 sites). Key finding: 67% achieving HiSCR75 at 52 weeks, durable to week 104 in 81% of completers. Primary gap: no published 2-year data in biologic-naive comparator.',
    dataSources: ['MSL field reports', 'HS registry data', 'Post-marketing surveillance', 'Ad board transcripts'],
    sizeLabel: '1.9 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'IL-17A/F vs IL-17A-Only Competitor Differentiation Brief',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Competitive Intelligence Report',
    dateCreated: '2026-05-10',
    summary: 'MSL-ready scientific exchange guide comparing bimekizumab (IL-17A+F), secukinumab (IL-17A), and ixekizumab (IL-17A) across psoriasis, PsA, and HS — IL-17F contribution data, PASI 90/100 comparisons, and HiSCR head-to-head evidence synthesis. Includes objection-handling guide for each competitor.',
    dataSources: ['Published Phase 3 trial data', 'AAD / EADV 2025 abstracts', 'MSL interaction logs', 'Payer formulary reports'],
    sizeLabel: '1.7 MB',
    provenance: 'synthesized',
  },
];
