// Artifact library — outputs completed agent tasks have produced.
// Default fill: Alexion template. Overwrite per demo.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — Q2 2026',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-04-14',
    summary: 'Full Q2 Strategy-to-Action: ISP pillars, MO coverage, prioritised insights, proposed actions, and Gap Radar suggestions.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Med Info queries', 'Congress debriefs', 'PubMed'],
    sizeLabel: '2.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'ASH 2025 Debrief — Biosimilar & Oral Inhibitor Signals',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-04-09',
    summary: 'Synthesized read on the three dominant scientific themes at ASH 2025 with competitor visibility and recommended actions.',
    dataSources: ['ASH 2025 abstracts', 'Session transcripts', 'Social commentary'],
    sizeLabel: '1.8 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART3',
    title: 'NMOSD Emerging KOL Map — April 2026',
    type: 'interactive',
    agent: 'LUCA',
    taskType: 'KOL Selection & Profiling',
    dateCreated: '2026-04-10',
    summary: 'Live KOL map with emerging-voice highlights and sentiment-shift overlays. 2 new names crossed the watch threshold this cycle.',
    dataSources: ['PubMed', 'Congress programs', 'CRM interaction history', 'Digital signals'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'Community Switch-Stability Narrative v1',
    type: 'pptx',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-04-07',
    summary: 'One-page-equivalent slide deck on switch-stability for community infusion centers. Co-sourced from AI1 + AI4.',
    dataSources: ['MSL field notes', 'Ad board transcripts'],
    sizeLabel: '3.1 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'gMG Refractory Subgroup Dossier — Draft',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Evidence Generation',
    dateCreated: '2026-04-02',
    summary: 'Draft refractory-subgroup evidence pack for the gMG guideline steering committee. Requires HEOR sign-off before distribution.',
    dataSources: ['Ad board transcripts', 'PubMed', 'Internal RWE'],
    sizeLabel: '4.2 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART6',
    title: 'ASH 2025 → ASH 2026 Sentiment Trend',
    type: 'interactive',
    agent: 'ARIA',
    taskType: 'Congress Intelligence',
    dateCreated: '2026-04-01',
    summary: 'Year-over-year sentiment shift across scientific themes, competitor visibility, and social amplification.',
    dataSources: ['ASH 2024 abstracts', 'ASH 2025 abstracts', 'Social commentary'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
];
