// Actionable insights — Demo Brief §5.
// Default fill: Alexion template. Overwrite per demo.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'Infusion-burden concern persists with Soliris',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 3,
    recency: '2026-03',
    summary: 'Community hematologists continue to cite biweekly infusion burden as a decision point, but switching inertia remains high even where Ultomiris is appropriate.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community hematologist', location: 'Charlotte, NC', quote: 'Patients who are stable are stable — I don’t want to mess with it, even though the dosing interval would be easier.', date: '2026-03-14' },
      { type: 'Ad board',        role: 'Academic hematologist',  location: 'Boston, MA',     quote: 'The switching data are convincing on paper but we need a cleaner community-facing algorithm.',           date: '2026-02-22' },
      { type: 'Med Info query',  role: 'Infusion center nurse',  location: 'Phoenix, AZ',    quote: 'Asked for a switching protocol sheet we can hand to scheduling.',                                            date: '2026-03-30' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.87,
    provenance: 'synthesized',
  },
  {
    id: 'AI2',
    title: 'RWE gap — long-term NMOSD outcomes',
    priority: 'High',
    lpRefs: ['LP1', 'LP4'], moRefs: ['MO1', 'MO3'],
    recurrence: 2,
    recency: '2026-03',
    summary: 'NMOSD specialists are sequencing C5 vs IL-6 vs CD19 inhibitors without head-to-head long-term data. Real-world retention and relapse-free survival data requested.',
    sourceInsights: [
      { type: 'Congress debrief', role: 'NMOSD specialist',      location: 'AAN 2026',       quote: 'We’re making sequencing decisions on 2-year data that should be made on 5-year data.',                     date: '2026-03-05' },
      { type: 'MSL interaction',  role: 'Neuroimmunologist',     location: 'Minneapolis, MN', quote: 'Any real-world relapse-free data past year 3 would change how I counsel patients.',                        date: '2026-03-18' },
    ],
    status: 'Validated',
    confidenceScore: 0.82,
    provenance: 'synthesized',
  },
  {
    id: 'AI3',
    title: 'gMG guideline positioning opportunity',
    priority: 'Medium',
    lpRefs: ['LP3'], moRefs: ['MO3'],
    recurrence: 2,
    recency: '2026-02',
    summary: 'Current gMG guidelines position C5 inhibition neutrally. Steering-committee KOLs open to strengthening with additional refractory-subgroup evidence.',
    sourceInsights: [
      { type: 'Ad board', role: 'gMG guideline steering member', location: 'Virtual', quote: 'Bring us the refractory subgroup data and we have something to work with.', date: '2026-02-09' },
    ],
    status: 'Triaged',
    confidenceScore: 0.71,
    provenance: 'synthesized',
  },
  {
    id: 'AI4',
    title: 'Switch-stability concerns from community centers',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 2,
    recency: '2026-04',
    summary: 'Community infusion centers want a patient-facing switch-stability narrative; current MSL materials read as academic.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Infusion center director', location: 'Indianapolis, IN', quote: 'Our patients ask us, not their doctor. We need something we can hand them.', date: '2026-04-02' },
      { type: 'Ad board',        role: 'Community hematologist',   location: 'Nashville, TN',    quote: 'Make the switch case in one page and we’ll act on it.',                   date: '2026-03-27' },
    ],
    status: 'Validated',
    confidenceScore: 0.79,
    provenance: 'synthesized',
  },
  {
    id: 'AI5',
    title: 'Pediatric aHUS evidence gap',
    priority: 'Medium',
    lpRefs: ['LP5'], moRefs: ['MO1'],
    recurrence: 1,
    recency: '2026-03',
    summary: 'Pediatric nephrologists lack confident long-term dosing guidance for younger aHUS patients; registry data haven’t surfaced in MSL briefings.',
    sourceInsights: [
      { type: 'Med Info query', role: 'Pediatric nephrologist', location: 'Seattle, WA', quote: 'Is there anything past the 3-year pediatric cohort? Families are asking.', date: '2026-03-22' },
    ],
    status: 'Captured',
    confidenceScore: 0.64,
    provenance: 'synthesized',
  },
];
