// Actionable insights — UCB demo.
// VEGA-led narrative: MO2 (MA impact measurement) is the intentional Gap driving the demo moment.
// No language positioning Aurivian as a replacement for UCB's internal tool — additive framing only.

export const INSIGHTS = [
  {
    id: 'AI1',
    title: 'MA leadership cannot quantify field medical contribution to outcomes',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2'],
    recurrence: 5,
    recency: '2026-05',
    summary: 'Internal stakeholder interviews and quarterly review outputs consistently show that UCB MA leadership tracks MSL activity volume (meetings, calls, events) but cannot connect those activities to scientific alignment shifts, insight generation rate, or downstream prescribing behavior. The reporting gap is not a data problem — the data exists in field systems. It is a synthesis and attribution problem.',
    sourceInsights: [
      { type: 'Internal stakeholder interview', role: 'Head of Medical Affairs, UCB Immunology', location: 'Brussels', quote: 'I can tell you how many MSL interactions we had this quarter. I cannot tell you what they changed.', date: '2026-04-15' },
      { type: 'Internal stakeholder interview', role: 'VP Medical Affairs, UCB North America', location: 'Atlanta, GA', quote: 'Our board wants to see the return on the MA investment. We don\'t have a number we can stand behind right now.', date: '2026-04-22' },
      { type: 'KPI benchmarking report', role: 'Medical Affairs benchmarking study', location: 'Industry', quote: 'Only 23% of pharma MA organizations have a validated model for attributing scientific exchange activity to measurable HCP behavior change.', date: '2026-03-01' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.94,
    provenance: 'synthesized',
  },
  {
    id: 'AI2',
    title: 'Biologic-naïve HS patients facing 4–6 month payer delay for Bimzelx',
    priority: 'High',
    lpRefs: ['LP1', 'LP3'], moRefs: ['MO1'],
    recurrence: 4,
    recency: '2026-05',
    summary: 'Dermatologists are consistently reporting that payer step therapy requirements — demanding documented TNF-alpha failure before approving Bimzelx in biologic-naïve HS — are creating a 4–6 month treatment delay in patients who would be appropriate candidates earlier. The clinical consequence is avoidable disease progression. No prior-auth support materials currently exist for field use.',
    sourceInsights: [
      { type: 'MSL field report', role: 'Community dermatologist', location: 'Chicago, IL', quote: 'I have patients who are clearly Bimzelx candidates. My hands are tied until they fail on adalimumab. That takes months and their disease gets worse.', date: '2026-05-03' },
      { type: 'Ad board summary', role: 'Academic dermatologist, HS specialist', location: 'London, UK', quote: 'The step therapy language in the payer criteria was written before the current Bimzelx HS data existed. It needs to be challenged with updated evidence.', date: '2026-04-14' },
      { type: 'MSL field report', role: 'Community dermatologist', location: 'Munich, Germany', quote: 'I need a one-page summary I can hand to P&T committee reviewers that makes the earlier-use case with the real-world data.', date: '2026-05-07' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.88,
    provenance: 'synthesized',
  },
  {
    id: 'AI3',
    title: 'IL-17A/F differentiation not translating to prescribing decisions in community',
    priority: 'Medium',
    lpRefs: ['LP4'], moRefs: ['MO4'],
    recurrence: 3,
    recency: '2026-04',
    summary: 'Academic dermatologists understand the dual IL-17A+F inhibition rationale clearly. Community dermatologists do not yet translate the mechanism into a prescribing preference. Competitor real-world data is filling the conversation gap that Bimzelx mechanism content hasn\'t reached — particularly among the mid-volume prescribers who see the most PsO and PsA patients.',
    sourceInsights: [
      { type: 'MSL interaction', role: 'Community dermatologist', location: 'Phoenix, AZ', quote: 'I know the IL-17F story in theory. I don\'t have a patient case that makes me reach for it over something I already know.', date: '2026-04-08' },
      { type: 'Congress debrief', role: 'Community dermatologist', location: 'AAD 2025', quote: 'The mechanism talk was compelling. I just need to know what it means for my patients who haven\'t responded fully to Cosentyx.', date: '2026-03-09' },
    ],
    status: 'Validated',
    confidenceScore: 0.79,
    provenance: 'synthesized',
  },
  {
    id: 'AI4',
    title: 'Insight-to-action triage gap: 69% of field insights not actioned within 90 days',
    priority: 'High',
    lpRefs: ['LP2'], moRefs: ['MO2', 'MO3'],
    recurrence: 3,
    recency: '2026-05',
    summary: 'VEGA ROMI analysis shows that 69% of MSL-captured insights are not progressing to a defined action within 90 days. The gap is structural: insights are captured in field systems but there is no systematic triage process that routes them to NOVA strategy-to-action review or assigns an owner. High-quality field intelligence is sitting inert.',
    sourceInsights: [
      { type: 'Internal KPI review', role: 'VEGA analysis engine', location: 'ucb-prod-azure', quote: 'Insight-to-action conversion rate: 31% (90-day window). Target: 60%. Gap: 29 percentage points. Primary bottleneck: triage ownership undefined.', date: '2026-05-01' },
      { type: 'Internal stakeholder interview', role: 'Medical Affairs Operations Lead', location: 'Brussels', quote: 'We know insights are being captured. We don\'t have a reliable way to know which ones are being acted on and which are just sitting in the system.', date: '2026-04-29' },
    ],
    status: 'Prioritised',
    confidenceScore: 0.91,
    provenance: 'synthesized',
  },
  {
    id: 'AI5',
    title: 'Neurology KOL mapping for seizure pipeline: 18-month window opening',
    priority: 'Medium',
    lpRefs: ['LP5'], moRefs: ['MO5'],
    recurrence: 2,
    recency: '2026-04',
    summary: 'The UCB seizure pipeline program has an 18-month window before data readouts make KOL engagement critical. Current neurology/epileptology KOL mapping is sparse — no tier structure, no congress tracking, no sentiment baseline. Establishing relationships now, before competitive data emerges, is the highest-leverage action available for the pipeline.',
    sourceInsights: [
      { type: 'Publication analysis', role: 'NOVA analysis engine', location: 'PubMed', quote: '14 epileptologists with >20 publications on acute seizure rescue identified; none are currently on the UCB neurology engagement list.', date: '2026-04-11' },
      { type: 'Congress speaker tracking', role: 'NOVA congress monitor', location: 'AES 2025', quote: '3 of the 14 identified KOLs gave plenary or symposium presentations at AES 2025. No UCB MSL interaction recorded at the same event.', date: '2026-12-08' },
    ],
    status: 'Triaged',
    confidenceScore: 0.72,
    provenance: 'synthesized',
  },
];
