// KOL roster — UCB demo.
// Bimzelx (psoriasis / PsA / AS / HS) + seizure portfolio (Briviact / Vimpat / Fintepla).
// Product IDs: 'bimzelx' | 'ucb-seizure-pipeline'

export const KOL_DATA = [
  {
    id: 'kol-1',
    name: 'Mark Lebwohl',
    institution: 'Icahn School of Medicine at Mount Sinai',
    city: 'New York', country: 'USA', region: 'Northeast',
    specialty: 'Dermatology / Psoriasis',
    influenceScore: 97,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 7,
    publications: 390,
    focusAreas: ['Plaque psoriasis treatment guidelines', 'Biologic sequencing', 'IL-17/IL-23 pathway'],
    conferenceAppearances: ['AAD 2025', 'EADV 2025'],
    recommendedStrategy: 'Primary psoriasis guideline anchor — leverage for Bimzelx IL-17A/F dual mechanism differentiation vs Cosentyx/Taltz. Priority advisory board role.',
    email: '',
  },
  {
    id: 'kol-2',
    name: 'Craig Leonardi',
    institution: 'Saint Louis University School of Medicine',
    city: 'St. Louis', country: 'USA', region: 'Midwest',
    specialty: 'Dermatology / Psoriasis',
    influenceScore: 91,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 5,
    publications: 280,
    focusAreas: ['IL-17 bispecific clinical trials', 'Head-to-head biologic comparisons', 'Psoriasis RWE'],
    conferenceAppearances: ['AAD 2025', 'EADV 2025'],
    recommendedStrategy: 'IL-17A/F mechanism champion — extensive head-to-head comparator experience. Ideal for Bimzelx vs Cosentyx/Taltz RWE co-authorship.',
    email: '',
  },
  {
    id: 'kol-3',
    name: 'Alice Gottlieb',
    institution: 'Icahn School of Medicine at Mount Sinai',
    city: 'New York', country: 'USA', region: 'Northeast',
    specialty: 'Dermatology / Psoriasis / PsA',
    influenceScore: 89,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 4,
    publications: 310,
    focusAreas: ['PsA biologic efficacy', 'IL-17 vs TNF sequencing', 'Skin-joint continuum'],
    conferenceAppearances: ['AAD 2025', 'EULAR 2026', 'ACR 2026'],
    recommendedStrategy: 'PsA cross-specialty voice — bridges dermatology and rheumatology. Key for Bimzelx dual-specialty positioning in PsA scientific exchange.',
    email: '',
  },
  {
    id: 'kol-4',
    name: 'Diamant Thaçi',
    institution: 'University of Lübeck — Comprehensive Center for Inflammation Medicine',
    city: 'Lübeck', country: 'Germany', region: 'Europe',
    specialty: 'Dermatology / Psoriasis / PsA',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 3,
    publications: 260,
    focusAreas: ['European IL-17 guideline leadership', 'Psoriasis comorbidities', 'Biologic safety profiles'],
    conferenceAppearances: ['EADV 2025', 'EULAR 2026'],
    recommendedStrategy: 'European guideline leader — primary influence on EADV psoriasis guidelines. Prioritize for Bimzelx European share-of-voice strategy and EADV 2025 data follow-up.',
    email: '',
  },
  {
    id: 'kol-5',
    name: 'Laura Coates',
    institution: 'University of Oxford',
    city: 'Oxford', country: 'UK', region: 'Europe',
    specialty: 'Rheumatology / PsA / Axial SpA',
    influenceScore: 88,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 4,
    publications: 195,
    focusAreas: ['PsA treat-to-target', 'nr-axSpA treatment algorithms', 'GRAPPA guideline development'],
    conferenceAppearances: ['EULAR 2026', 'ACR 2026', 'EADV 2025'],
    recommendedStrategy: 'GRAPPA/EULAR axSpA anchor — co-author on GRAPPA treatment recommendations. Key voice for Bimzelx nr-axSpA positioning vs Cosentyx.',
    email: '',
  },
  {
    id: 'kol-6',
    name: 'Gregor Jemec',
    institution: 'University of Copenhagen / Zealand University Hospital',
    city: 'Copenhagen', country: 'Denmark', region: 'Europe',
    specialty: 'Dermatology / Hidradenitis Suppurativa',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 3,
    publications: 230,
    focusAreas: ['HS pathogenesis and staging', 'Biologic therapy in HS', 'HS disease burden'],
    conferenceAppearances: ['EADV 2025', 'IHS 2025'],
    recommendedStrategy: 'HS global KOL — primary author on HS scoring systems and biologic guidelines. Essential advisory board anchor for Bimzelx HS real-world evidence programme.',
    email: '',
  },
  {
    id: 'kol-7',
    name: 'Christos Zouboulis',
    institution: 'Dessau Medical Center / Brandenburg Medical School',
    city: 'Dessau', country: 'Germany', region: 'Europe',
    specialty: 'Dermatology / Hidradenitis Suppurativa',
    influenceScore: 87,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 2,
    publications: 215,
    focusAreas: ['HS inflammation pathways', 'European HS treatment consensus', 'Biologic durability in HS'],
    conferenceAppearances: ['EADV 2025', 'IHS 2025'],
    recommendedStrategy: 'European HS mechanism leader — engagement gap detected (last contact 8 weeks). Re-engage with Bimzelx HS IL-17F evidence package; public narrative drifting toward Novartis platform. Priority window: before EADV 2026 (October).',
    email: '',
  },
  {
    id: 'kol-8',
    name: 'Iain McInnes',
    institution: 'University of Glasgow',
    city: 'Glasgow', country: 'UK', region: 'Europe',
    specialty: 'Rheumatology / PsA / Systemic Inflammation',
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 5,
    publications: 340,
    focusAreas: ['IL-17 immunobiology', 'PsA systemic inflammation', 'Biologic mechanism comparison'],
    conferenceAppearances: ['EULAR 2026', 'ACR 2026'],
    recommendedStrategy: 'Global rheumatology immunobiology anchor — key influence on IL-17 mechanism narrative across Europe. Ideal for Bimzelx dual IL-17A/F scientific exchange and EULAR symposia.',
    email: '',
  },
  {
    id: 'kol-9',
    name: 'Philip Mease',
    institution: 'Swedish Medical Center / Providence Health — University of Washington',
    city: 'Seattle', country: 'USA', region: 'West',
    specialty: 'Rheumatology / PsA',
    influenceScore: 85,
    engagementTier: 'Tier 2',
    productAlignment: ['bimzelx'],
    recentInteractions: 3,
    publications: 290,
    focusAreas: ['PsA clinical trial design', 'ACR/EULAR PsA outcome measures', 'Biologic comparative effectiveness'],
    conferenceAppearances: ['ACR 2026', 'EULAR 2026'],
    recommendedStrategy: 'US PsA trial leader — extensive comparative effectiveness publication record. Opportunity for Bimzelx PsA real-world co-publication ahead of ACR 2026.',
    email: '',
  },
  {
    id: 'kol-10',
    name: 'Ingo Helbig',
    institution: "Children's Hospital of Philadelphia (CHOP) / University of Pennsylvania",
    city: 'Philadelphia', country: 'USA', region: 'Northeast',
    specialty: 'Pediatric Epilepsy / Dravet Syndrome',
    influenceScore: 92,
    engagementTier: 'Tier 1',
    productAlignment: ['ucb-seizure-pipeline'],
    recentInteractions: 4,
    publications: 165,
    focusAreas: ['Dravet syndrome genetics', 'SCN1A-related epilepsy', 'Adjunctive antiseizure therapy'],
    conferenceAppearances: ['AES 2025', 'ILAE 2025'],
    recommendedStrategy: 'Dravet syndrome global leader — primary voice on SCN1A genetics and Fintepla mechanisms. Essential for UCB seizure pipeline KOL foundation.',
    email: '',
  },
  {
    id: 'kol-11',
    name: 'Rima Nabbout',
    institution: 'Necker-Enfants Malades Hospital — Paris Cité University',
    city: 'Paris', country: 'France', region: 'Europe',
    specialty: 'Pediatric Neurology / Dravet Syndrome',
    influenceScore: 90,
    engagementTier: 'Tier 1',
    productAlignment: ['ucb-seizure-pipeline'],
    recentInteractions: 3,
    publications: 148,
    focusAreas: ['Dravet syndrome treatment', 'Developmental epileptic encephalopathy', 'European epilepsy guidelines'],
    conferenceAppearances: ['ECNS 2025', 'ILAE 2025'],
    recommendedStrategy: 'European Dravet syndrome anchor — primary European voice on fenfluramine/Fintepla and adjunctive therapy sequencing. Key for pipeline European KOL strategy.',
    email: '',
  },
  {
    id: 'kol-12',
    name: 'Joseph Sullivan',
    institution: 'UCSF Benioff Children\'s Hospital',
    city: 'San Francisco', country: 'USA', region: 'West',
    specialty: 'Pediatric Neurology / Dravet Syndrome',
    influenceScore: 86,
    engagementTier: 'Tier 1',
    productAlignment: ['ucb-seizure-pipeline'],
    recentInteractions: 3,
    publications: 118,
    focusAreas: ['Dravet syndrome clinical management', 'Adjunctive ASM efficacy', 'Patient/family engagement in Dravet'],
    conferenceAppearances: ['AES 2025', 'CNS Summit 2025'],
    recommendedStrategy: 'US Dravet clinical voice — UCSF Dravet centre sees high patient volume. Co-development opportunity for UCB seizure pipeline patient outcomes framework.',
    email: '',
  },
  {
    id: 'kol-13',
    name: 'Solomon Moshé',
    institution: 'Montefiore Medical Center / Albert Einstein College of Medicine',
    city: 'Bronx', country: 'USA', region: 'Northeast',
    specialty: 'Neurology / Epilepsy',
    influenceScore: 88,
    engagementTier: 'Tier 1',
    productAlignment: ['ucb-seizure-pipeline'],
    recentInteractions: 2,
    publications: 280,
    focusAreas: ['Seizure development mechanisms', 'Focal epilepsy', 'Antiseizure drug mechanisms'],
    conferenceAppearances: ['AES 2025', 'ILAE 2025'],
    recommendedStrategy: 'Broad epilepsy science anchor — foundational seizure mechanism expertise relevant to UCB REST paradigm positioning. Low recent engagement — re-engage with pipeline science brief.',
    email: '',
  },
  {
    id: 'kol-14',
    name: 'Helen Cross',
    institution: 'Great Ormond Street Hospital / University College London',
    city: 'London', country: 'UK', region: 'Europe',
    specialty: 'Pediatric Epilepsy / Dravet Syndrome',
    influenceScore: 84,
    engagementTier: 'Tier 2',
    productAlignment: ['ucb-seizure-pipeline'],
    recentInteractions: 2,
    publications: 190,
    focusAreas: ['Pediatric epilepsy surgery', 'Dravet syndrome management', 'UK epilepsy guidelines'],
    conferenceAppearances: ['ECNS 2025', 'BPNA 2025'],
    recommendedStrategy: 'UK pediatric epilepsy voice — GOSH Dravet centre and NICE guideline influencer. Key engagement ahead of UK seizure pipeline regulatory pathway.',
    email: '',
  },
  {
    id: 'kol-15',
    name: 'Georg Schett',
    institution: 'University of Erlangen-Nuremberg — Department of Internal Medicine 3',
    city: 'Erlangen', country: 'Germany', region: 'Europe',
    specialty: 'Immunology / Rheumatology',
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['bimzelx'],
    recentInteractions: 3,
    publications: 410,
    focusAreas: ['IL-17 immunobiology', 'Bone destruction in inflammatory arthritis', 'Biologic mechanism differentiation'],
    conferenceAppearances: ['EULAR 2026', 'ACR 2026'],
    recommendedStrategy: 'European immunobiology powerhouse — foundational IL-17F pathway publications directly support dual IL-17A/F Bimzelx differentiation narrative. Priority for scientific exchange programme.',
    email: '',
  },
  {
    id: 'kol-16',
    name: 'Kamran Ghoreschi',
    institution: 'Charité Universitätsmedizin Berlin',
    city: 'Berlin', country: 'Germany', region: 'Europe',
    specialty: 'Dermatology / Immunology',
    influenceScore: 82,
    engagementTier: 'Tier 2',
    productAlignment: ['bimzelx'],
    recentInteractions: 2,
    publications: 145,
    focusAreas: ['Th17 cell differentiation', 'IL-17 pathway in psoriasis', 'Translational immunology'],
    conferenceAppearances: ['EADV 2025', 'DDG 2026'],
    recommendedStrategy: 'IL-17 translational science bridge — Charité Th17/IL-17 pathway expertise anchors dual IL-17A/F scientific credibility in Germany. Engage ahead of EADV 2025.',
    email: '',
  },
  {
    id: 'kol-17',
    name: 'Claudia Kemper',
    institution: 'National Heart, Lung, and Blood Institute (NHLBI) / NIH',
    city: 'Bethesda', country: 'USA', region: 'Northeast',
    specialty: 'Immunology / Systems Biology',
    influenceScore: 80,
    engagementTier: 'Tier 2',
    productAlignment: ['bimzelx'],
    recentInteractions: 1,
    publications: 130,
    focusAreas: ['IL-17 pathway crosstalk', 'Complement-IL-17 interactions', 'Systemic inflammation networks'],
    conferenceAppearances: ['AAI 2026'],
    recommendedStrategy: 'NIH immunology science credibility — IL-17 crosstalk publications strengthen Bimzelx dual-mechanism scientific narrative. Low engagement — explore advisory role for pipeline science.',
    email: '',
  },
];
